# Generated by Django 5.0.2 on 2025-04-08 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextChallenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('recommended_time', models.IntegerField(help_text='Recommended time in minutes')),
                ('content', models.TextField()),
                ('word_count', models.IntegerField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='text_challenges.language')),
            ],
        ),
    ]
